### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by kud1ing** [NyxCode/heaven-on-earth#1]
According to https://lifehacker.com/set-your-macs-wallpaper-with-a-terminal-command-1728551470 this could work:

`osascript -e ‘tell application “Finder” to set desktop picture to POSIX file “/path/to/picture.jpg”’`

**Comment by NyxCode** [comment]
Thanks for the research - in theory, it should work now.
Do you have a machine to test it on?

**Comment by kud1ing** [comment]
Not right now, but i am convinced this will work. Closing. Thank you.
